import { StyleSheet } from "react-native";
import { Colors, fonts } from "@/constants/theme";
export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: Colors.common.white },
  header: {
    height: 56,
    paddingHorizontal: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  content: { paddingHorizontal: 24, paddingBottom: 24 },
  progress: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 14,
    marginBottom: 26,
  },
  dot: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: Colors.gray[4],
    alignItems: "center",
    justifyContent: "center",
  },
  dotActive: { backgroundColor: Colors.gray[9] },
  connector: {
    width: 14,
    height: 1,
    backgroundColor: Colors.gray[4],
    marginHorizontal: 5,
  },
  save: { marginLeft: "auto", paddingVertical: 8 },
  subtitle: {
    ...fonts.body4_r_14,
    color: Colors.gray[7],
    marginTop: 6,
    marginBottom: 28,
  },
  field: { paddingVertical: 20, gap: 24 },
  label: { ...fonts.body2_m_14, color: Colors.gray[8], marginBottom: 8 },
  input: {
    ...fonts.sub4_sb_14,
    minHeight: 48,
    borderWidth: 1,
    borderColor: Colors.gray[3],
    borderRadius: 8,
    backgroundColor: Colors.common.white,
    paddingHorizontal: 14,
    color: Colors.gray[11],
  },
  select: {
    minHeight: 48,
    borderWidth: 1,
    borderColor: Colors.gray[3],
    borderRadius: 8,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  textarea: {
    ...fonts.body2_m_14,
    minHeight: 132,
    textAlignVertical: "top",
    padding: 14,
    color: Colors.gray[11],
  },
  textBox: { borderWidth: 1, borderColor: Colors.gray[3], borderRadius: 8 },
  counter: {
    ...fonts.caption4_m_12,
    color: Colors.gray[7],
    alignSelf: "flex-end",
    paddingRight: 12,
    paddingBottom: 8,
  },
  footer: {
    paddingHorizontal: 24,
    paddingTop: 12,
    backgroundColor: Colors.common.white,
  },
  button: {
    height: 48,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.primary.default,
  },
  disabled: { backgroundColor: Colors.primary.light },
  buttonText: { ...fonts.sub4_sb_14, color: Colors.common.white },
  row: { flexDirection: "row", alignItems: "center", gap: 8 },
  overlay: { flex: 1, justifyContent: "flex-end" },
  sheet: {
    maxHeight: "92%",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 20,
  },
  handle: {
    width: 44,
    height: 4,
    borderRadius: 2,
    backgroundColor: Colors.gray[4],
    alignSelf: "center",
    marginTop: 8,
    marginBottom: 20,
  },
  sheetHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 24,
  },
  chips: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  chip: {
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: Colors.gray[1],
  },
  chipActive: { backgroundColor: Colors.gray[11] },
  dropdown: {
    maxHeight: 180,
    borderWidth: 1,
    borderColor: Colors.gray[3],
    borderRadius: 8,
    marginTop: 6,
    backgroundColor: Colors.common.white,
  },
  option: { paddingHorizontal: 14, paddingVertical: 12 },
  stepper: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: Colors.gray[2],
    borderRadius: 8,
  },
  stepperButton: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  quantity: {
    ...fonts.sub3_sb_16,
    minWidth: 36,
    textAlign: "center",
    backgroundColor: Colors.common.white,
    borderRadius: 5,
    padding: 5,
  },
  empty: {
    minHeight: 170,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: Colors.gray[3],
    borderRadius: 10,
    backgroundColor: Colors.gray[1],
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
  },
  card: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderWidth: 1,
    borderColor: Colors.gray[3],
    padding: 10,
    borderRadius: 10,
    marginBottom: 10,
  },
  thumb: {
    width: 80,
    height: 80,
    borderRadius: 7,
    backgroundColor: Colors.gray[2],
  },
  itemTag: {
    alignSelf: "flex-start",
    borderRadius: 3,
    paddingHorizontal: 4,
    paddingVertical: 2,
    backgroundColor: "#EFF6FF",
  },
  editItemButton: {
    alignSelf: "flex-start",
    width: 36,
    height: 36,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.gray[1],
  },
  addItemFab: {
    position: "absolute",
    right: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: Colors.gray[9],
    alignItems: "center",
    justifyContent: "center",
  },
  itemEditorField: { gap: 8, marginBottom: 36 },
  itemEditorButton: { height: 52, borderRadius: 10 },
  itemEditorButtonText: { ...fonts.sub3_sb_16, color: Colors.common.white },
  itemEditorActions: { flexDirection: "row", gap: 8, paddingTop: 16 },
  deleteItemButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: Colors.primary.default,
    backgroundColor: Colors.common.white,
  },
});
